CREATE DATABASE VINABOOK
go
USE VINABOOK
go


CREATE TABLE DANHMUC(
	MaDM INT identity(01,1) NOT NULL PRIMARY KEY,
	TenDM NVARCHAR(200)
)

CREATE TABLE PHATHANHSACH(
	MAPHATHANH INT identity(01, 1) NOT NULL PRIMARY KEY,
	TENNPT NVARCHAR(200),
)
CREATE TABLE SACH(
	MASACH INT identity(01, 1) NOT NULL PRIMARY KEY,
	TENSACH NVARCHAR(200),
	GIATIEN FLOAT,
	SLTONKHO INT,
	NGAYNHAPHANG DATE,
	NHAXUATBAN NVARCHAR(200),
	MADM int,
	CONSTRAINT FK_MADANHMUC1 foreign key(MADM) references DANHMUC(MADM)
)


create table KHACHHANG(
	MAKH INT identity(01,1) NOT NULL PRIMARY KEY,
	TENKH NVARCHAR(200),
	SDT varchar(220),
	DIACHI NVARCHAR(MAX),
	Email NVARCHAR(MAX),
	Account NVARCHAR(MAX),
	Pass NVARCHAR(MAX),
	MATICHLUY INT
	
	CONSTRAINT FK_MATICHLUY2 FOREIGN KEY (MATICHLUY) REFERENCES TICHLUY (MATICHLUY)
)


create table TACGIA(
	MATG INT identity(01, 1) NOT NULL PRIMARY KEY,
	TENTG NVARCHAR(MAX),
	NGAYSINHTG date
)


CREATE TABLE NHANVIEN(
	MANV INT identity(01, 1) NOT NULL PRIMARY KEY,
	TENNV NVARCHAR(MAX),
	GIOITINH NVARCHAR(MAX),
	VITRI NVARCHAR(MAX),
	NGAYSINH NVARCHAR(MAX),
	NGAYTHUE NVARCHAR(MAX),
	DIACHINV NVARCHAR(MAX),
	SDT varchar(MAX),
	LUONG int
)


create table shipper(
	MASHIPPER INT identity(01,1) NOT NULL PRIMARY KEY,
	TENCTY NVARCHAR(MAX),
	SDTCTY BIGINT
)


CREATE TABLE BINHLUAN(
	MABL INT identity(01, 1) NOT NULL PRIMARY KEY,
	MAKH INT NOT NULL,
	MASACH INT,
	DANHGIA int,
	CONSTRAINT FK_MAKH1 FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_MASACH1 FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
)


CREATE TABLE DONHANG(
	MADH INT identity(01, 1) NOT NULL PRIMARY KEY,
	MANV INT,
	MASHIPPER INT,
	MAKH INT NOT NULL,
	TENSHIPPER NVARCHAR(MAX),
	SDTSHIPPER varchar(20),
	DIACHIGH NVARCHAR(MAX),
	PTDATHANG NVARCHAR(MAX),
	NGAYDATHANG DATE,
	NGAYDUDINHSHIP DATE,
	TONGGIA FLOAT,
	MATRANGTHAI INT

	CONSTRAINT FK_MATT1 FOREIGN KEY(MATRANGTHAI) REFERENCES TRANGTHAI(MATRANGTHAI),
	CONSTRAINT FK_MAKH2 FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_MASHIPPER1 FOREIGN KEY(MASHIPPER) REFERENCES SHIPPER(MASHIPPER),
	CONSTRAINT FK_MANV4 FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
)

CREATE TABLE DONHANG_CHITIET(
	MADH INT NOT NULL,
	MASACH INT,
	SOLUONG INT, 
	CONSTRAINT PR_MADH_MASACH PRIMARY KEY(MADH, MASACH),
	CONSTRAINT FK_MADH FOREIGN KEY(MADH) REFERENCES DONHANG(MADH),
	CONSTRAINT FK_MASACH FOREIGN KEY(MASACH) REFERENCES SACH(MASACH)
)

CREATE TABLE SANGTAC(
	MATG INT NOT NULL,
	MASACH INT,
	NAMST INT,
	CONSTRAINT PR_MATG_MASACH PRIMARY KEY(MATG, MASACH),
	CONSTRAINT FK_MATG FOREIGN KEY(MATG) REFERENCES TACGIA(MATG),
	CONSTRAINT FK_MASACH2 FOREIGN KEY(MASACH) REFERENCES SACH(MASACH)
)

CREATE TABLE HOPTAC(
	MATG INT NOT NULL,
	MAPHATHANH INT NOT NULL,
	NGAYKIHOPDONG DATE,
	NGAYHETHAN DATE,

	CONSTRAINT PR_MATG_MAPHATHANH PRIMARY KEY(MATG, MAPHATHANH),
	CONSTRAINT FK_MATG3 FOREIGN KEY(MATG) REFERENCES TACGIA(MATG),
	CONSTRAINT FK_MAPHATHANH FOREIGN KEY(MAPHATHANH) REFERENCES PHATHANHSACH(MAPHATHANH)
)

create table TICHLUY(
	MATICHLUY INT identity(01, 1) NOT NULL PRIMARY KEY,
	DISCOUNT FLOAT,
	TENTICHLUY NVARCHAR(200)
)

create table TRANGTHAI
(
	MATRANGTHAI INT NOT NULL PRIMARY KEY,
	TENTRANGTHAI NVARCHAR(200)
)

CREATE TABLE HOADON
(
	MAHOADON INT identity(01, 1) NOT NULL PRIMARY KEY,
	NGAYTAOMA DATE,
	MAPHATHANH INT

	CONSTRAINT FK_MAPH1 FOREIGN KEY(MAPHATHANH) REFERENCES PHATHANHSACH(MAPHATHANH)
)

CREATE TABLE HOADON_CHITIET
(
	SOLUONGBANDAU INT,
	GIANHAP FLOAT,
	TENSANPHAM NVARCHAR(MAX),
	MASACH INT,
	MAHOADON INT

	CONSTRAINT FK_MANH1 FOREIGN KEY(MAHOADON) REFERENCES HOADON(MAHOADON),
	CONSTRAINT FK_MASACH3 FOREIGN KEY(MASACH) REFERENCES SACH(MASACH)
)




DROP TABLE HOADON_CHITIET
DROP TABLE TRANGTHAI
drop table binhluan
drop table TICHLUY
drop table DONHANG_CHITIET
drop table NHANVIEN
drop table [dbo].[shipper]
drop table DONHANG
DROP TABLE KHACHHANG
DROP TABLE sach
DROP TABLE SANGTAC
DROP DATABASE VINABOOK
GO

